In [5]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder


In [6]:
df = pd.read_csv("data-one-hot-encoder.csv")

In [7]:
df.head
#top five rows

<bound method NDFrame.head of       Id Colour Country
0      1    Red     USA
1      2    Red     USA
2      3   Blue      UK
3      4  Green  Canada
4      5  Green  Canada
..   ...    ...     ...
295  296   Blue     USA
296  297  Green     USA
297  298  Green      UK
298  299  Green  Canada
299  300   Blue     USA

[300 rows x 3 columns]>

In [8]:
df.tail
#bottom five rows

<bound method NDFrame.tail of       Id Colour Country
0      1    Red     USA
1      2    Red     USA
2      3   Blue      UK
3      4  Green  Canada
4      5  Green  Canada
..   ...    ...     ...
295  296   Blue     USA
296  297  Green     USA
297  298  Green      UK
298  299  Green  Canada
299  300   Blue     USA

[300 rows x 3 columns]>

In [10]:
df.dtypes


Id          int64
Colour     object
Country    object
dtype: object

In [12]:
df["Colour"].unique()

array(['Red', 'Blue', 'Green'], dtype=object)

In [14]:
df["Country"].unique()

array(['USA', 'UK', 'Canada'], dtype=object)

In [15]:
ohe = OneHotEncoder()

In [16]:
print(ohe)

OneHotEncoder()


In [17]:
ohe.fit_transform(df[["Colour","Country"]]).toarray()

array([[0., 0., 1., 0., 0., 1.],
       [0., 0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0.],
       ...,
       [0., 1., 0., 0., 1., 0.],
       [0., 1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 1.]])

In [18]:
feature_array = ohe.fit_transform(df[["Colour","Country"]]).toarray()

In [24]:
print(feature_array)

[[0. 0. 1. 0. 0. 1.]
 [0. 0. 1. 0. 0. 1.]
 [1. 0. 0. 0. 1. 0.]
 ...
 [0. 1. 0. 0. 1. 0.]
 [0. 1. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 1.]]


In [19]:
ohe.categories_

[array(['Blue', 'Green', 'Red'], dtype=object),
 array(['Canada', 'UK', 'USA'], dtype=object)]

In [20]:
feature_labels = ohe.categories_

In [21]:
np.array(feature_labels).ravel()
#saving label names

array(['Blue', 'Green', 'Red', 'Canada', 'UK', 'USA'], dtype=object)

In [22]:
feature_labels = np.array(feature_labels).ravel()

In [23]:
print(feature_labels)

['Blue' 'Green' 'Red' 'Canada' 'UK' 'USA']


In [26]:
pd.DataFrame(feature_array,columns = feature_labels )

Blue  Green  Red  Canada   UK  USA
0     0.0    0.0  1.0     0.0  0.0  1.0
1     0.0    0.0  1.0     0.0  0.0  1.0
2     1.0    0.0  0.0     0.0  1.0  0.0
3     0.0    1.0  0.0     1.0  0.0  0.0
4     0.0    1.0  0.0     1.0  0.0  0.0
..    ...    ...  ...     ...  ...  ...
295   1.0    0.0  0.0     0.0  0.0  1.0
296   0.0    1.0  0.0     0.0  0.0  1.0
297   0.0    1.0  0.0     0.0  1.0  0.0
298   0.0    1.0  0.0     1.0  0.0  0.0
299   1.0    0.0  0.0     0.0  0.0  1.0

[300 rows x 6 columns]

In [27]:
features = pd.DataFrame(feature_array,columns = feature_labels )

In [28]:
print(features)

     Blue  Green  Red  Canada   UK  USA
0     0.0    0.0  1.0     0.0  0.0  1.0
1     0.0    0.0  1.0     0.0  0.0  1.0
2     1.0    0.0  0.0     0.0  1.0  0.0
3     0.0    1.0  0.0     1.0  0.0  0.0
4     0.0    1.0  0.0     1.0  0.0  0.0
..    ...    ...  ...     ...  ...  ...
295   1.0    0.0  0.0     0.0  0.0  1.0
296   0.0    1.0  0.0     0.0  0.0  1.0
297   0.0    1.0  0.0     0.0  1.0  0.0
298   0.0    1.0  0.0     1.0  0.0  0.0
299   1.0    0.0  0.0     0.0  0.0  1.0

[300 rows x 6 columns]


In [29]:
features.head

<bound method NDFrame.head of      Blue  Green  Red  Canada   UK  USA
0     0.0    0.0  1.0     0.0  0.0  1.0
1     0.0    0.0  1.0     0.0  0.0  1.0
2     1.0    0.0  0.0     0.0  1.0  0.0
3     0.0    1.0  0.0     1.0  0.0  0.0
4     0.0    1.0  0.0     1.0  0.0  0.0
..    ...    ...  ...     ...  ...  ...
295   1.0    0.0  0.0     0.0  0.0  1.0
296   0.0    1.0  0.0     0.0  0.0  1.0
297   0.0    1.0  0.0     0.0  1.0  0.0
298   0.0    1.0  0.0     1.0  0.0  0.0
299   1.0    0.0  0.0     0.0  0.0  1.0

[300 rows x 6 columns]>

In [32]:
#join the new data frame with the original data frame 
pd.concat([df,features],axis = 1)

Id Colour Country  Blue  Green  Red  Canada   UK  USA
0      1    Red     USA   0.0    0.0  1.0     0.0  0.0  1.0
1      2    Red     USA   0.0    0.0  1.0     0.0  0.0  1.0
2      3   Blue      UK   1.0    0.0  0.0     0.0  1.0  0.0
3      4  Green  Canada   0.0    1.0  0.0     1.0  0.0  0.0
4      5  Green  Canada   0.0    1.0  0.0     1.0  0.0  0.0
..   ...    ...     ...   ...    ...  ...     ...  ...  ...
295  296   Blue     USA   1.0    0.0  0.0     0.0  0.0  1.0
296  297  Green     USA   0.0    1.0  0.0     0.0  0.0  1.0
297  298  Green      UK   0.0    1.0  0.0     0.0  1.0  0.0
298  299  Green  Canada   0.0    1.0  0.0     1.0  0.0  0.0
299  300   Blue     USA   1.0    0.0  0.0     0.0  0.0  1.0

[300 rows x 9 columns]

In [33]:
df_new = pd.concat([df,features],axis = 1)

In [34]:
df_new.head()

Id Colour Country  Blue  Green  Red  Canada   UK  USA
0   1    Red     USA   0.0    0.0  1.0     0.0  0.0  1.0
1   2    Red     USA   0.0    0.0  1.0     0.0  0.0  1.0
2   3   Blue      UK   1.0    0.0  0.0     0.0  1.0  0.0
3   4  Green  Canada   0.0    1.0  0.0     1.0  0.0  0.0
4   5  Green  Canada   0.0    1.0  0.0     1.0  0.0  0.0